#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2011 Plivo Team. See LICENSE for details.

import sys
import optparse
from plivo.rest.freeswitch.outbound_server import PlivoOutboundServer


def opt():
    parser = optparse.OptionParser()
    parser.add_option("-c", "--config", action="store", type="string",
                      dest="filename", help="set config file to FILE", metavar="FILE",
                      default="./plivo_rest.conf")

    parser.add_option("-f", "--foreground",
                      action="store_true", dest="foreground", default=False,
                      help="run foreground")

    parser.add_option("-d", "--daemon",
                      action="store_true", dest="daemon", default=False,
                      help="run as daemon")

    (options, args) = parser.parse_args()
    return (parser, options, args)



if __name__ == '__main__':
    parser, options, args = opt()
    configfile = options.filename
    if options.foreground:
        daemon = False
    elif options.daemon:
        daemon = True
    else:
        parser.print_help()
        sys.exit(0)
#    try:
    rest_server = PlivoOutboundServer(configfile, daemon=daemon)
    rest_server.start()
#    except Exception, e:
#        print "ERROR %s" % str(e)
#        sys.exit(1)
    sys.exit(0)
