#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2011 Plivo Team. See LICENSE for details.
"""
Daemonizer for python scripts.
"""

import plivo.utils.daemonize as daemonize
daemonize.main()
